baseURL = "/"
languageCode = "it"
title = "Assembler Studio"
enableEmoji = true
enableRobotsTXT = true
defaultContentLanguage = "it"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 

[params]
  description = "Portfolio dei progetti e siti web realizzati da Assembler Computer"
  author = "Assembler Computer"
  showDarkToggle = true 

[pagination]
  paginate = 6

[menu]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Contatti"
  url = "/contatti"
  weight = 2

[languages]
  [languages.it]
    weight = 1
    languageName = "Italiano"
    title = "Portfolio Assembler"
    contentDir = "content/it"

  [languages.en]
    weight = 2
    languageName = "English"
    title = "Assembler Portfolio"
    contentDir = "content/en"